### ISSUE TITLE
Fnf vs george neto

### ISSUE THREAD

**Issue by pocoyogeorgeneto** [kem0x/FNF-ModShaders#2]
https://drive.google.com/file/d/1IJdlNsj8Gw_JhW8r6xdvE5i_QvnChChN/view?usp=drivesdk

**Comment by moxie-coder** [comment]
> https://drive.google.com/file/d/1IJdlNsj8Gw_JhW8r6xdvE5i_QvnChChN/view?usp=drivesdk

don’t use GitHub to self advertise your crap

**Comment by moxie-coder** [comment]
![IMG_5901](https://github.com/user-attachments/assets/4724ed1c-54dd-4e62-821f-e777afcdf97c)
